services:
  dss.com:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app
      - ./dreamy-data:/dreamy-data
    ports:
      - "80:80"
  rm_worker:
    build:
      context: .
      dockerfile: rm_worker.dockerfile
    volumes:
      - ./app/:/app
      - ./dreamy-data:/dreamy-data